# Generated by Django 3.2.7 on 2021-09-27 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210921_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='variation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.ingredient'),
        ),
    ]
