# Generated by Django 3.2.7 on 2021-09-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210927_1858'),
        ('orders', '0002_auto_20210927_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProductDetail',
            new_name='OrderProductIngredient',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('in process', 'In Process'), ('pending', 'Pending')], default='pending', max_length=16),
        ),
    ]
