# Generated by Django 3.2.7 on 2021-09-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
