# Generated by Django 3.2.7 on 2021-09-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210927_1858'),
        ('users', '0002_alter_user_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
